# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\devin\Desktop\Tiled2NES\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(849, 598)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tableFiles = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableFiles.sizePolicy().hasHeightForWidth())
        self.tableFiles.setSizePolicy(sizePolicy)
        self.tableFiles.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableFiles.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tableFiles.setAlternatingRowColors(False)
        self.tableFiles.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableFiles.setColumnCount(2)
        self.tableFiles.setObjectName("tableFiles")
        self.tableFiles.setRowCount(0)
        self.tableFiles.horizontalHeader().setVisible(True)
        self.tableFiles.horizontalHeader().setSortIndicatorShown(True)
        self.tableFiles.horizontalHeader().setStretchLastSection(False)
        self.tableFiles.verticalHeader().setVisible(True)
        self.gridLayout.addWidget(self.tableFiles, 1, 0, 1, 7)
        self.checkCodeGuards = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkCodeGuards.sizePolicy().hasHeightForWidth())
        self.checkCodeGuards.setSizePolicy(sizePolicy)
        self.checkCodeGuards.setObjectName("checkCodeGuards")
        self.gridLayout.addWidget(self.checkCodeGuards, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 849, 26))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd_File = QtWidgets.QAction(MainWindow)
        self.actionAdd_File.setObjectName("actionAdd_File")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setEnabled(False)
        self.actionExport.setObjectName("actionExport")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionClearTable = QtWidgets.QAction(MainWindow)
        self.actionClearTable.setObjectName("actionClearTable")
        self.menu_File.addAction(self.actionAdd_File)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionExport)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionClearTable)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tableFiles.setSortingEnabled(True)
        self.checkCodeGuards.setStatusTip(_translate("MainWindow", "Add code guards to prevent multiple inclusions"))
        self.checkCodeGuards.setText(_translate("MainWindow", "Code guards"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionAdd_File.setText(_translate("MainWindow", "Add File(s)..."))
        self.actionAdd_File.setStatusTip(_translate("MainWindow", "Add one or more Tiled map CSV files"))
        self.actionAdd_File.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionExport.setText(_translate("MainWindow", "Export..."))
        self.actionExport.setToolTip(_translate("MainWindow", "Export"))
        self.actionExport.setStatusTip(_translate("MainWindow", "Export to C source"))
        self.actionExport.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionExit.setText(_translate("MainWindow", "E&xit"))
        self.actionExit.setStatusTip(_translate("MainWindow", "Exit Tiled2NES"))
        self.actionClearTable.setText(_translate("MainWindow", "Clear"))
        self.actionClearTable.setStatusTip(_translate("MainWindow", "Resets everything to start over again"))
